name: firebase_login
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  binder:
    path: ../../packages/binder
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  font_awesome_flutter: ^8.10.0
  gap: ^1.2.0
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.5
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
